# Generated by Django 5.0.6 on 2024-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
