# Generated by Django 5.0.6 on 2024-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_app', '0002_country_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
