# Generated by Django 5.0.6 on 2024-05-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_app', '0004_states_s_image_states_s_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='s_image',
        ),
        migrations.RemoveField(
            model_name='states',
            name='s_text',
        ),
    ]
