# Generated by Django 5.0.6 on 2024-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_app', '0005_remove_states_s_image_remove_states_s_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='image',
            field=models.ImageField(null=True, upload_to='country_image'),
        ),
        migrations.AddField(
            model_name='airline',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='states',
            name='image',
            field=models.ImageField(null=True, upload_to='country_image'),
        ),
        migrations.AddField(
            model_name='states',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
